url: "https://annalebelle.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Annabelle Flores Bonilla" # the name of your site, e.g. ACME Corp.
description: "Neuroscientist and Science Communicator"
