menu:

- {name: 'publications', url: '/publications'}
- {name: 'sci-comm', url: '/sci-comm'}
- {name: 'mentorship', url: '/mentorship'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

mentorship:
- {name: 'Student Mentors Project', url: 'student-mentors-pucpr'}
- {name: 'NSF Graduate Research Fellowship Program (GRFP) Mentor', url: 'grfp-mentor-umass'}
- {name: 'PREP Near Peer Mentor', url: 'prep-mentor-umass'}
- {name: 'NSB Community and Social Coordinator', url: 'nsb-community-social-umass'}

social:
- {icon: 'github', link: 'https://github.com/annalebelle'}
- {icon: 'twitter', link: 'https://twitter.com/annalebelle'}
- {icon: 'instagram', link: 'https://instagram.com/annalebelle'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/annalebelle'}

contacts:
- {name: 'Annabelle Flores Bonilla', title: 'Neuroscience and Behavior PhD Candidate', department: 'Psychological and Brain Sciences', institution: 'University of Massachusetts', institution_address: 'Amherst, MA', email: 'afloresbonil@umass.edu', office: 'Morrill Science Center', image: 'assets/img/Profile Picture 2024.jpg'}
