menu:
- {name: 'awards', url: '/awards'}
- {name: 'publications', url: '/publications'}
- {name: 'science communication', url: '/science communication'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

Awards:
- {name: 'Awards for Research Funding and Professional Development', title: 'Society for Neuroscience', department: 'Trainee Professional Development Award (TDPA)', institution: '2024', institution_address: 'Awarded for the abstract titled A history of adolescent drinking increases myelination of axons within the corticotropin releasing factor-enriched subregion of the central amygdala in adult mice.', phone: 'Award for travel to the 2024 Society for Neuroscience Conference in Chicago, Illinois.', email: 'Attended events for professional development training.', office: 'Poster', image: 'assets/img/primary-investigator.jpg', url: 'awards'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
